version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - directory: /docker
    package-ecosystem: docker
    schedule:
      interval: weekly
